language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_deploy:
  - npm run build
  - chmod +x ./scripts/netlify_deploy.sh

deploy:
  provider: script
  script: scripts/netlify_deploy.sh
  skip_cleanup: true
  on:
    branch: master
